LAB 2
iis-powp-2018z-twist-backup/powp_rhymers_bridge pull request #23
Opened 2018-11-06 12:11 UTC by kamilasyp

2018-11-06 12:12 UTC, kamilasyp commented
LAB2

2018-11-12 15:39 UTC, kowallus requested changes
1 pts
3.1.4 point was done incorrectly. Tips in comments.

2018-11-12 15:39 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	private final IntLinkedList intLinkedList;
The goal of the lab was to make using IntLinkedList and IntArrayStack interchangeable.

2018-11-12 15:39 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/IntArray.java
> +public interface IntArray {
An empty interface!

2018-11-12 15:39 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/IntStack.java
> +		// TODO Auto-generated method stub
what about is the implementation?!

2018-11-12 15:39 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/FifoRhymer.java
> +	public IntStack temp = new IntStack();
Unimplemented class! It does not work :(

2018-11-12 15:39 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/FifoRhymer.java
> +public class FifoRhymer extends DefaultCountingOutRhymer {
Name FIFORhymer was better because FIFO is not a word

2018-11-12 15:39 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/ListRyhmersFactory.java
> +	public DefaultCountingOutRhymer GetStandardRhymer() {
should be getStandardRhymer! (from a lowercase)

2018-11-12 15:39 UTC, kowallus commented on src/main/java/stack/IntLinkedList.java
> +public class IntLinkedList implements IntLinked {
IntLinkedList and IntArrayStack should implement the same interface!

2018-11-18 08:44 UTC, kamilasyp commented
poprawione lab2

2018-12-03 11:55 UTC, kowallus reviewed
2.5 pts

Specific issues inlined in the code.
Final tasks are missing.
Commits polluted with project/compilation files

2018-12-03 11:55 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	protected Stack list;
"stack" rather than "list".
There should be a constructor: public DefaultCountingOutRhymer(Stack stack)

2018-12-03 11:55 UTC, kowallus commented on src/main/java/stack/IntArrayStack.java
> +    private int total = IS_EMPTY;
This should always remain -1!

2018-12-03 11:55 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/FifoRhymer.java
> +	public FifoRhymer(IntLinkedList list) {
parameter should be: (Stack stack)

2018-12-03 11:55 UTC, kowallus commented on src/main/java/edu/kis/vh/nursery/ArrayRyhmersFactory.java
> +//implementacja bez poprawek
Constructor parameter should specify stack type

2018-12-03 11:55 UTC, closed without merging